POST http://localhost:3001/api/blogs 
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1haWdndSIsImlkIjoiNWE5NmFjMGYxMjQxZTcxZWEzYTc2MjVhIiwiaWF0IjoxNTE5OTQ2MjY2fQ.55_-8Ey_43aEsd_cFRLMXvBX7sMnWDHyU3tJfo8NnOY

{
"title": "How to Become John", 
"author": "Markku Mehiläinen",
"url": "www.youtube.com",
"likes": 2,
"user": "5a96ac0f1241e71ea3a7625a"
}